# These are supported funding model platforms

github: [your-username]
# patreon: your-patreon-username
# open_collective: your-org
# ko_fi: your-username
# tidelift: npm/package-name
# custom: ["https://your-link.com"]
